### Exercise 4 Programming exercise

Assignment:
Implement the verification of matrix multiplication by Freivalds’ algorithm.
Starting with a correct product A × B = C (all three matrices are of size
n × n for some reasonably large n, try to corrupt some entries of C, and
check whether the algorithm is able to catch the mistake. Perform multiple
independent runs of the algorithm, to get a sense of how often it fails to detect
the error.

In [ ]:
import random

In [ ]:
import numpy as np
#choose n=4

#we generate random matrices A and B with numbers from 0 to 9, compute the product C and introduce an corrupted matrix C1

num_rows = 8
num_columns = 8
A = np.array([[random.randint(0,9) for j in range(num_rows)] for i in range(num_columns)])
B = np.array([[random.randint(0,9) for j in range(num_rows)] for i in range(num_columns)])

A= np.array([[1,2,3,4],[4,5,3,2],[1,5,7,2],[9,4,9,8]])

B= np.array([[9,4,9,8],[1,5,7,2],[1,2,3,4],[4,5,3,2]]).astype(int)

C=(A@B)
print(C)
C1=C-(np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0.0001],[0,0,0,0]]))

from random import random
import random

#this is the freivalds algrithm
# it gerenates a random vector with 0 or 1 in the size of the quadratic matrices A and B
#substracts the vector from B and from C, computed the product of A and the substracted B vector and
#finanlly the differences between this result and the substracted B vector
def freivalds(A,B,C):
    random_v = [random.randint(0, 1) for e in range(4)]
    result=(A@(B@random_v))-(C@random_v)
    yesorno=(result==np.array([0,0,0,0])).all()
    return yesorno

#now we test the freivalds algorithm k times and count how often it is wrong
#the algorithm is wrong, when it outputs True, i.e. the two matrices are the same, because they are not because we introduced an error
#return1 summarizes the k iterations yielding true only if all iterations
def testfreivalds(k):
    return1=True
    for i in range (k):
        result=freivalds(A,B,C1)
        return1=return1 & result
    return return1

#here we report the results of the testing step for k=100, k=10 and k= 100000
#we also report the number of errors

k=10
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p2=p

print("For k = 10, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p2, "and p <= (1/2)**10 =", (p2<=(1/2)**10))

k=100
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):#algorithm is wrong
        count+=1
    p=count/100
    p1=p

print("For k = 100, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p1, "and p <= (1/2)**100 =", p1<=(1/2)**100)


k=100000
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p3=p

print("For k = 100000, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p3, "and p <= (1/2)**100000 =", p3<=(1/2)**100000)
import matplotlib.pyplot as plt

[[ 30  40  44  32]
 [ 52  57  86  58]
 [ 29  53  71  50]
 [126 114 160 132]]
For k = 10, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**10 = True
For k = 100, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**100 = True
For k = 100000, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**100000 = True


# Does the theoretical analysis of the error probability hold up?

The theoretical analysis or the error probability states that the error p is smaller than (1/2)^k for k iterations.
We repeated the test 10 times for each k value.
We observed that the bigger the k value, the smaller the probability that the error probability was below the theoretical boundary.
Hence, the theoretical analysis or the error probability didnt hold up in every case.


# Is the error rate influenced by the amount of corruption you introduce in C?

We repeat the steps above with a bigger error for the C matrix and more erronous matrix values at all. We observed that the more and the bigger the introduced errors in the matrix are, the smaller the probablity of the error was.



In [ ]:
C1=C-(np.array([[0,0,0,0],[1,0,0,0],[0,1,0,1],[0,1,0,0]]))
k=10
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p2=p

print("For k = 10, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p2, "and p <= (1/2)**10 =", (p2<=(1/2)**10))

k=100
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):#algorithm is wrong
        count+=1
    p=count/100
    p1=p

print("For k = 100, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p1, "and p <= (1/2)**100 =", p1<=(1/2)**100)


k=100000
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p3=p

print("For k = 100000, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p3, "and p <= (1/2)**100000 =", p3<=(1/2)**100000)

For k = 10, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**10 = True
For k = 100, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**100 = True
For k = 100000, and 100 iterations  0 times the algorithm was wrong, hence p= 0.0 and p <= (1/2)**100000 = True


Is
it influenced by the input matrices A and B you pick?

Answer:
We observed that if there is less variation in the values of the matrices, the error probability is bigger compared to our frst example where we used the same code except the the range of values that were used for A and B.

In [ ]:
import numpy as np
#choose n=4

num_rows = 8
num_columns = 8
A = np.array([[random.randint(0,5) for j in range(num_rows)] for i in range(num_columns)])
B = np.array([[random.randint(0,5) for j in range(num_rows)] for i in range(num_columns)])

C=(A@B)
print(C)
C1=C-(np.array([[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0.0001],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]))

print(C1)
from random import random
import random

def freivalds(A,B,C):
    random_v = [random.randint(0, 1) for e in range(8)]
    result=(A@(B@random_v))-(C@random_v)
    yesorno=(result==np.array([0,0,0,0,0,0,0,0])).all()
    return yesorno

#test k times
def testfreivalds(k):
    return1=True
    for i in range (k):
        result=freivalds(A,B,C1)
        return1=return1 & result
        return return1

k=10
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p2=p

print("For k = 10, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p2, "and p <= (1/2)**10 =", (p2<=(1/2)**10))

k=100
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):#algorithm is wrong
        count+=1
    p=count/100
    p1=p

print("For k = 100, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p1, "and p <= (1/2)**100 =", p1<=(1/2)**100)


k=100000
count=0
for i in range (100):
    return1= testfreivalds(k)
    if (return1==True):
        count+=1
    p=count/100
    p3=p

print("For k = 100000, and 100 iterations ",count, "times the algorithm was wrong, hence p=",p3, "and p <= (1/2)**100000 =", p3<=(1/2)**100000)
import matplotlib.pyplot as plt

[[40 51 53 50 58 64 76 78]
 [44 48 31 43 44 40 63 64]
 [56 85 49 44 57 58 90 90]
 [38 62 29 23 31 35 56 57]
 [36 39 46 34 52 39 58 55]
 [46 63 46 53 48 62 71 80]
 [28 44 35 32 40 45 57 54]
 [42 51 23 29 30 30 54 62]]
[[40.     51.     53.     50.     58.     64.     76.     78.    ]
 [44.     48.     31.     43.     44.     40.     63.     64.    ]
 [56.     85.     49.     44.     57.     58.     90.     89.9999]
 [38.     62.     29.     23.     31.     35.     56.     57.    ]
 [36.     39.     46.     34.     52.     39.     58.     55.    ]
 [46.     63.     46.     53.     48.     62.     71.     80.    ]
 [28.     44.     35.     32.     40.     45.     57.     54.    ]
 [42.     51.     23.     29.     30.     30.     54.     62.    ]]
For k = 10, and 100 iterations  55 times the algorithm was wrong, hence p= 0.55 and p <= (1/2)**10 = False
For k = 100, and 100 iterations  52 times the algorithm was wrong, hence p= 0.52 and p <= (1/2)**100 = False
For k = 100000, and 100 iterat

We conclude, that as the theoretical analysis of the error probability states, the more iterations we use for the freivalds algorithm, the smaller the error probability is. The opposite we observe for the variation in the values of A and B: the smaller the variation, the higher the error. The same holds for the error we introduce in C and: the higher and the more frequent ther error, the smaller the probability for the algorithm to be wrong.

In [ ]:
#!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
import os
print(os.getcwd())
from google.colab import drive
drive.mount('/content/drive/')
os.chdir("/content/drive/My Drive/Colab Notebooks")
!jupyter nbconvert --to pdf 'Advanced Algorithms_Ex4_4.ipynb'

/content/drive/My Drive/Colab Notebooks
Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
[NbConvertApp] Converting notebook Advanced Algorithms_Ex4_4.ipynb to pdf
[NbConvertApp] Writing 45506 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 57194 bytes to Advanced Algorithms_Ex4_4.pdf
